metno/py-mmd-tools

.github/pull_request_template.md
Summary: I have added a template for the PR descriptions. This PR demonstrates the usage.
Related issue: #15 
Suggested reviewer(s): @epifanio @ElodieFZ 
Checklist:   [This is not relevant for this PR, since it is not a code contribution]
The checklist is based on the S-ENDA conventions and definition of done. The above points are not necessarily relevant to all contributions. In that case, please add a short explanation to help the reviewer.
=> Template for PR descriptions

.github/pull_request_template.md
**Summary**: Specified that reviewer should tick the checklist
**Related issue**: #15 
**Suggested reviewer(s)**: None - this is a very minor change
**Checklist**: Not relevant
=> Test pr template

script/README.md, script/checkMMD.py
**Summary**: Simple check of MMD file
**Related issue**: #29 
**Suggested reviewer(s)**: @mortenwh @abigailla 
=> #29 add script

py_mmd_tools/templates/mmd_template.xml
**Summary**: Solves issue with activity_type
**Related issue**: #46 
**Suggested reviewer(s)**: @TAlonglong 
=> #46: bug fix

py_mmd_tools/templates/mmd_template.xml
**Summary**: mmd template used checksum_type - changed to using checksum
**Related issue**: #55 
**Suggested reviewer(s)**: @TAlonglong 
=> #55: bug fix

py_mmd_tools/nc_to_mmd.py, py_mmd_tools/templates/mmd_template.xml, script/nc_to_mmd
**Summary**:
Need to add netcdf-local-path option
Also optimized chuck size on slow file locations like mount over cifs and nfs
Fixed also a new line issue in mmd_template.xml
@mortenwh 
=> Issue56 add netcdf-local-path option

py_mmd_tools/check_mmd.py, py_mmd_tools/xml_utils.py, script/check_MMD, tests/test_nc_to_mmd.py
**Summary**:
**Related issue**: #59 
=> Issue59 check mmd

py_mmd_tools/check_mmd.py, py_mmd_tools/nc_to_mmd.py, script/nc_to_mmd, tests/test_check_mmd.py
=> Add .html to thredds urls

py_mmd_tools/__init__.py, py_mmd_tools/config.py, setup.cfg, setup.py
=> #70: Need config.py file to allow for installation

README.md
**Summary**: Demo of CI
**Related issue**: #81 
**Suggested reviewer(s)**: @aheimsbakk 
=> added a dot at end of sentence

py_mmd_tools/__init__.py, pyproject.toml, setup.cfg
Some fixes to allow pip install directly from source package/
=> Add pyproject.toml and fix setup.cfg

Dockerfile.tests, py_mmd_tools/mmd_elements.yaml, py_mmd_tools/nc_to_mmd.py, script/check_MMD, script/yaml2adoc, tests/README.md, tests/data/mmd_strict.xsd, tests/test_check_mmd.py, tests/test_mmd_yaml_vs_xsd.py, tests/test_nc_to_mmd.py, tests/test_odajson_to_mmd.py, tests/test_xml_util.py, tests/test_yaml2adoc.py
**Summary**: Changed default values for personnel following discussion in metno/mmd#125
**Related issue**: #91 
**Suggested reviewer(s)**: @TAlonglong 
=> #91: changed default values

py_mmd_tools/nc_to_mmd.py, tests/test_nc_to_mmd.py
**Summary**: Closes #127 
**Related issue**: #127 
**Suggested reviewer(s)**: @johtoblan 
=> #127: use 4 decimals for the polygons

py_mmd_tools/nc_to_mmd.py, tests/test_nc_to_mmd.py
**Summary**: closes #126 
**Related issue**: #126 
**Suggested reviewer(s)**: @johtoblan 
=> Issue126 metadata status

py_mmd_tools/mmd_elements.yaml, py_mmd_tools/nc_to_mmd.py
**Summary**: Removes acdd_ext for instrument and platform short_name.
**Related issue**:  
Closes #107 
**Suggested reviewer(s)**: @mortenwh 
=> Issue107 Remove acdd ext

py_mmd_tools/nc_to_mmd.py, script/nc2mmd.py, tests/test_nc_to_mmd.py
**Summary**:
Adds -c as a flag to nc2mmd.py script, to toggle if checksum should be calculated (Default is True)
Closes #147 
@mortenwh 
@ElodieFZ 
=> Issue147 optional checksum

py_mmd_tools/nc_to_mmd.py, tests/test_nc_to_mmd.py
**Summary**: see issue description
**Related issue**: closes #153 
**Suggested reviewer(s)**: @johtoblan 
=> #153: test and updated code

py_mmd_tools/nc_to_mmd.py, py_mmd_tools/templates/nc_attributes_template.adoc
**Summary**: see #161 
**Related issue**: closes #161 
=> Issue161 logging

py_mmd_tools/mmd_elements.yaml, py_mmd_tools/nc_to_mmd.py, tests/test_nc_to_mmd.py
**Summary**: closes #178 
**Related issue**: #178
=> Issue178 license

py_mmd_tools/mmd_elements.yaml
**Summary**: closes #194 
**Related issue**: #194 
=> #194: updated description text

py_mmd_tools/mmd_elements.yaml
**Summary**: closes #201 
**Related issue**: #201 
=> #201: added links to MMD and GCMD controlled vocabularies

py_mmd_tools/nc_to_mmd.py, tests/test_nc_to_mmd.py
**Summary**: closes #203 
**Related issue**: #203 
=> Issue203 space in attrs

py_mmd_tools/mmd_elements.yaml, py_mmd_tools/nc_to_mmd.py, tests/test_nc_to_mmd.py
**Summary**: closes #206 
**Related issue**: #206 
=> Issue206 publisher elems

py_mmd_tools/nc_to_mmd.py, tests/test_nc_to_mmd.py
**Summary**: closes #208 
**Related issue**: #208 
=> Issue208 instrument vocab bug

py_mmd_tools/mmd_elements.yaml, py_mmd_tools/nc_to_mmd.py, tests/test_nc_to_mmd.py
=> #215: bug fix, improved description, and updated test

py_mmd_tools/mmd_elements.yaml
**Summary**: closes #213 
**Related issue**: #213
=> #213: changed description text

py_mmd_tools/__init__.py
=> Updated package version

README.md
Added installation docs assuming Conda will be used.
=> Issue165 update installation docs

py_mmd_tools/nc_to_mmd.py, tests/test_nc_to_mmd.py
=> #234: check for empty string instead of boolean false

py_mmd_tools/nc_to_mmd.py, tests/test_nc2mmd_script.py, tests/test_nc_to_mmd.py
=> #253: issue warning if invalid url

py_mmd_tools/nc_to_mmd.py
**Summary**:
**Related issue**: #266
=> Added additional naming authorities

py_mmd_tools/nc_to_mmd.py, tests/test_nc_to_mmd.py
**Summary**:
**Related issue**: #267 
=> Correcting error messages

py_mmd_tools/nc_to_mmd.py, tests/test_nc_to_mmd.py
=> #274: allow custom dataset citation

py_mmd_tools/mmd_elements.yaml, py_mmd_tools/templates/nc_attributes_template.adoc, py_mmd_tools/yaml_to_adoc.py
=> Issue238 creator role

py_mmd_tools/templates/nc_attributes_template.adoc
=> change heading

py_mmd_tools/nc_to_mmd.py, tests/test_nc_to_mmd.py
=> #291: test and solution

pyproject.toml
**Summary**:
Fixed path to source folder in project metadata.
=> Fix routing to source folder

py_mmd_tools/nc_to_mmd.py
=> add time to exception list for CF keywords

py_mmd_tools/mmd_elements.yaml, py_mmd_tools/templates/nc_attributes_template.adoc, tests/test_nc_to_mmd.py
=> corrections after review by Elinah!

py_mmd_tools/nc_to_mmd.py, tests/data/reference_nc_header_missing_title.json, tests/test_nc_to_mmd.py
**Summary**:
Needed to explicitly handle accessing title field in json mode, as this is used before check to see if it is set.
=> Add error handeling if title not set in json input

py_mmd_tools/nc_to_mmd.py, py_mmd_tools/script/nc2mmd.py
=> #325: update

py_mmd_tools/script/ncheader2json.py, tests/test_ncheader2json.py
=> #321: handle int16

py_mmd_tools/nc_to_mmd.py, tests/test_nc_to_mmd.py
=> #327: solution and test

README.md, py_mmd_tools/nc_to_mmd.py
=> #332: add standard names to list

py_mmd_tools/nc_to_mmd.py, tests/test_nc_to_mmd.py
=> #273: strip spaces around keywords

py_mmd_tools/script/ncheader2json.py, tests/test_ncheader2json.py
=> add handeling of np int32
